
default::
	g++ -Wall zcompress.cpp -o zcompress -lpcap  -L. -lCFFEXtraderapi -lssl -lcrypto
	g++ -Wall problem-1.cpp -o problem-1 -lpcap  -L. -lCFFEXtraderapi -lssl -lcrypto

clean::
	rm -f zcompress problem-1

